################################ Shield IO ################################ 
# IO Seven-segment display select
set_property PACKAGE_PIN P9 [get_ports {io_sel[0]}]                # 7-seg display Q1, AN1 bank A pin 43
    set_property IOSTANDARD LVCMOS33 [get_ports {io_sel[0]}]
set_property PACKAGE_PIN N9 [get_ports {io_sel[1]}]                # 7-seg display Q2, AN2 bank A pin 42
    set_property IOSTANDARD LVCMOS33 [get_ports {io_sel[1]}]
set_property PACKAGE_PIN R8 [get_ports {io_sel[2]}]                # 7-seg display Q3, AN3 bank A pin 8
    set_property IOSTANDARD LVCMOS33 [get_ports {io_sel[2]}]
#set_property PACKAGE_PIN P8 [get_ports {io_sel[3]}]                # 7-seg display Q4, AN4 bank A pin 9 UNUSED, 3 7-SEG DISPLAYS
#    set_property IOSTANDARD LVCMOS33 [get_ports {io_sel[3]}]
    
# IO Seven-segment display
set_property PACKAGE_PIN T5 [get_ports {io_seg[0]}]                    # 7-seg display R5, A->RA bank A pin 5
    set_property IOSTANDARD LVCMOS33 [get_ports {io_seg[0]}]
set_property PACKAGE_PIN R5 [get_ports {io_seg[1]}]                    # 7-seg display R5, B->RB bank A pin 6
    set_property IOSTANDARD LVCMOS33 [get_ports {io_seg[1]}]
set_property PACKAGE_PIN T9 [get_ports {io_seg[2]}]                    # 7-seg display R5, C->RC bank A pin 48
    set_property IOSTANDARD LVCMOS33 [get_ports {io_seg[2]}]
set_property PACKAGE_PIN R6 [get_ports {io_seg[3]}]                    # 7-seg display R5, D->RD bank A pin 46
    set_property IOSTANDARD LVCMOS33 [get_ports {io_seg[3]}]
set_property PACKAGE_PIN R7 [get_ports {io_seg[4]}]                    # 7-seg display R5, E->RE bank A pin 45
    set_property IOSTANDARD LVCMOS33 [get_ports {io_seg[4]}]
set_property PACKAGE_PIN T7 [get_ports {io_seg[5]}]                    # 7-seg display R5, F->RF bank A pin 3
    set_property IOSTANDARD LVCMOS33 [get_ports {io_seg[5]}]
set_property PACKAGE_PIN T8 [get_ports {io_seg[6]}]                    # 7-seg display R5, G->RF bank A pin 2
    set_property IOSTANDARD LVCMOS33 [get_ports {io_seg[6]}]
set_property PACKAGE_PIN T10 [get_ports {dp}]                          # 7-seg display R, RDP->DP bank A pin 49
    set_property IOSTANDARD LVCMOS33 [get_ports {dp}]
    
# IO DIP Switches
set_property PACKAGE_PIN D6 [get_ports {io_dip[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_dip[0]}]
    set_property PULLDOWN true [get_ports {io_dip[0]}]
set_property PACKAGE_PIN D5 [get_ports {io_dip[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_dip[1]}]
    set_property PULLDOWN true [get_ports {io_dip[1]}]
set_property PACKAGE_PIN F5 [get_ports {io_dip[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_dip[2]}]
    set_property PULLDOWN true [get_ports {io_dip[2]}]
set_property PACKAGE_PIN E5 [get_ports {io_dip[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_dip[3]}]
    set_property PULLDOWN true [get_ports {io_dip[3]}]
set_property PACKAGE_PIN G5 [get_ports {io_dip[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_dip[4]}]
    set_property PULLDOWN true [get_ports {io_dip[4]}]
set_property PACKAGE_PIN G4 [get_ports {io_dip[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_dip[5]}]
    set_property PULLDOWN true [get_ports {io_dip[5]}]
set_property PACKAGE_PIN D4 [get_ports {io_dip[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_dip[6]}]
    set_property PULLDOWN true [get_ports {io_dip[6]}]
set_property PACKAGE_PIN C4 [get_ports {io_dip[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_dip[7]}]
    set_property PULLDOWN true [get_ports {io_dip[7]}]
set_property PACKAGE_PIN E3 [get_ports {io_dip[8]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_dip[8]}]
    set_property PULLDOWN true [get_ports {io_dip[8]}]
set_property PACKAGE_PIN D3 [get_ports {io_dip[9]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_dip[9]}]
    set_property PULLDOWN true [get_ports {io_dip[9]}]
set_property PACKAGE_PIN C3 [get_ports {io_dip[10]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_dip[10]}]
    set_property PULLDOWN true [get_ports {io_dip[10]}]
set_property PACKAGE_PIN C2 [get_ports {io_dip[11]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_dip[11]}]
    set_property PULLDOWN true [get_ports {io_dip[11]}]
set_property PACKAGE_PIN C1 [get_ports {io_dip[12]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_dip[12]}]
    set_property PULLDOWN true [get_ports {io_dip[12]}]
set_property PACKAGE_PIN B1 [get_ports {io_dip[13]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_dip[13]}]
    set_property PULLDOWN true [get_ports {io_dip[13]}]
set_property PACKAGE_PIN M6 [get_ports {io_dip[14]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_dip[14]}]
    set_property PULLDOWN true [get_ports {io_dip[14]}]
set_property PACKAGE_PIN N6 [get_ports {io_dip[15]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_dip[15]}]
    set_property PULLDOWN true [get_ports {io_dip[15]}]
# set_property PACKAGE_PIN H5 [get_ports {io_dip[16]}]
#     set_property IOSTANDARD LVCMOS33 [get_ports {io_dip[16]}]
#         set_property PULLDOWN true [get_ports {io_dip[16]}]
# set_property PACKAGE_PIN H4 [get_ports {io_dip[17]}]
#     set_property IOSTANDARD LVCMOS33 [get_ports {io_dip[17]}]
#         set_property PULLDOWN true [get_ports {io_dip[17]}]
# set_property PACKAGE_PIN J3 [get_ports {io_dip[18]}]
#     set_property IOSTANDARD LVCMOS33 [get_ports {io_dip[18]}]
#         set_property PULLDOWN true [get_ports {io_dip[18]}]
# set_property PACKAGE_PIN H3 [get_ports {io_dip[19]}]
#     set_property IOSTANDARD LVCMOS33 [get_ports {io_dip[19]}]
#         set_property PULLDOWN true [get_ports {io_dip[19]}]
# set_property PACKAGE_PIN J5 [get_ports {io_dip[20]}]
#     set_property IOSTANDARD LVCMOS33 [get_ports {io_dip[20]}]
#         set_property PULLDOWN true [get_ports {io_dip[20]}]
# set_property PACKAGE_PIN J4 [get_ports {io_dip[21]}]
#     set_property IOSTANDARD LVCMOS33 [get_ports {io_dip[21]}]
#         set_property PULLDOWN true [get_ports {io_dip[21]}]
# set_property PACKAGE_PIN K3 [get_ports {io_dip[22]}]
#     set_property IOSTANDARD LVCMOS33 [get_ports {io_dip[22]}]
#         set_property PULLDOWN true [get_ports {io_dip[22]}]
# set_property PACKAGE_PIN K2 [get_ports {io_dip[23]}]
#     set_property IOSTANDARD LVCMOS33 [get_ports {io_dip[23]}]
#         set_property PULLDOWN true [get_ports {io_dip[23]}]

# IO Buttons
#btnU - s4
set_property PACKAGE_PIN C6 [get_ports{io_btn[0]}]                        # IO Button S4, S1 bank B pin 28
    set_property IOSTANDARD LVCMOS33 [get_ports {io_btn[0]}]
    set_property PULLDOWN true [get_ports {io_btn[0]}]

#btnC - s5
set_property PACKAGE_PIN C7 [get_ports{io_btn[1]}]                        # IO Button S5, S2 bank B pin 27
    set_property IOSTANDARD LVCMOS33 [get_ports {io_btn[1]}]
    set_property PULLDOWN true [get_ports {io_btn[1]}]
    
#btnD - s6
set_property PACKAGE_PIN A7 [get_ports{io_btn[2]}]                        # IO Button S6, S3 bank B pin 23
    set_property IOSTANDARD LVCMOS33 [get_ports {io_btn[2]}]
    set_property PULLDOWN true [get_ports {io_btn[2]}]
    
#btnL - s7
set_property PACKAGE_PIN B7 [get_ports{io_btn[3]}]                        # IO Button S7, S4 bank B pin 24
    set_property IOSTANDARD LVCMOS33 [get_ports {io_btn[3]}]
    set_property PULLDOWN true [get_ports {io_btn[3]}]
    
#btnR - s8
set_property PACKAGE_PIN P11 [get_ports{io_btn[4]}]                        # IO Button S8, S5 bank C pin 49
    set_property IOSTANDARD LVCMOS33 [get_ports {io_btn[4]}]
    set_property PULLDOWN true [get_ports {io_btn[4]}]
    
# LEDS
set_property PACKAGE_PIN B6 [get_ports {io_led[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_led[0]}]
set_property PACKAGE_PIN B5 [get_ports {io_led[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_led[1]}]
set_property PACKAGE_PIN A5 [get_ports {io_led[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_led[2]}]
set_property PACKAGE_PIN A4 [get_ports {io_led[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_led[3]}]
set_property PACKAGE_PIN B4 [get_ports {io_led[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_led[4]}]
set_property PACKAGE_PIN A3 [get_ports {io_led[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_led[5]}]
set_property PACKAGE_PIN F4 [get_ports {io_led[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_led[6]}]
set_property PACKAGE_PIN F3 [get_ports {io_led[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_led[7]}]
set_property PACKAGE_PIN F2 [get_ports {io_led[8]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_led[8]}]
set_property PACKAGE_PIN E1 [get_ports {io_led[9]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_led[9]}]
set_property PACKAGE_PIN B2 [get_ports {io_led[10]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_led[10]}]
set_property PACKAGE_PIN A2 [get_ports {io_led[11]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_led[11]}]
set_property PACKAGE_PIN E2 [get_ports {io_led[12]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_led[12]}]
set_property PACKAGE_PIN D1 [get_ports {io_led[13]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_led[13]}]
set_property PACKAGE_PIN E6 [get_ports {io_led[14]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_led[14]}]
set_property PACKAGE_PIN K5 [get_ports {io_led[15]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_led[15]}]
set_property PACKAGE_PIN G2 [get_ports {io_led[16]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_led[16]}]
set_property PACKAGE_PIN G1 [get_ports {io_led[17]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_led[17]}]
set_property PACKAGE_PIN H2 [get_ports {io_led[18]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_led[18]}]
set_property PACKAGE_PIN H1 [get_ports {io_led[19]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_led[19]}]
set_property PACKAGE_PIN K1 [get_ports {io_led[20]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_led[20]}]
set_property PACKAGE_PIN J1 [get_ports {io_led[21]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_led[21]}]
set_property PACKAGE_PIN L3 [get_ports {io_led[22]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_led[22]}]
set_property PACKAGE_PIN L2 [get_ports {io_led[23]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {io_led[23]}]
    
# HDMI - UNUSED
#set_property PACKAGE_PIN P1 [get_ports {hdmi_red[0]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_red[0]}]
#set_property PACKAGE_PIN N1 [get_ports {hdmi_red[1]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_red[1]}]
#set_property PACKAGE_PIN R1 [get_ports {hdmi_red[2]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_red[2]}]
#set_property PACKAGE_PIN R2 [get_ports {hdmi_red[3]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_red[3]}]

#set_property PACKAGE_PIN T2 [get_ports {hdmi_green[0]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_green[0]}]
#set_property PACKAGE_PIN R3 [get_ports {hdmi_green[1]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_green[1]}]
#set_property PACKAGE_PIN T3 [get_ports {hdmi_green[2]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_green[2]}]
#set_property PACKAGE_PIN T4 [get_ports {hdmi_green[3]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_green[3]}]

#set_property PACKAGE_PIN N4 [get_ports {hdmi_blue[0]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_blue[0]}]
#set_property PACKAGE_PIN M5 [get_ports {hdmi_blue[1]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_blue[1]}]
#set_property PACKAGE_PIN L5 [get_ports {hdmi_blue[2]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_blue[2]}]
#set_property PACKAGE_PIN P5 [get_ports {hdmi_blue[3]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_blue[3]}]

#set_property PACKAGE_PIN M1 [get_ports {hdmi_vs}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_vs}]
#set_property PACKAGE_PIN M2 [get_ports {hdmi_hs}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_hs}]
#set_property PACKAGE_PIN N13 [get_ports {hdmi_de}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_de}]
#set_property PACKAGE_PIN P13 [get_ports {hdmi_ck}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_ck}]